"""worker claim lease: claim_token, claimed_at

Revision ID: 867af545e9dd
Revises: 5d66ae57cfaa
Create Date: 2026-09-27 16:44:17.963008

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '867af545e9dd'
down_revision = '5d66ae57cfaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claim_token', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index('ix_deliveries_claim', ['claim_token', 'claimed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index('ix_deliveries_claim')
        batch_op.drop_column('claimed_at')
        batch_op.drop_column('claim_token')

    # ### end Alembic commands ###
